dist: xenial
language: node_js
sudo: false

branches:
    except:
        - /^v[0-9]/

before_install:
    - npm i -g npm

install:
    - npm i -g firebase firebase-tools
    - firebase setup:emulators:firestore
    - npm install --prefix=./firestore/rules-test
    - npm install --prefix=./functions

script:
    - npm run --prefix=./firestore/rules-test test

deploy:
    provider: firebase
    skip_cleanup: true
    on:
        tags: false
        branch: master
