dist: xenial
language: node_js
node_js:
    - "10"

branches:
    except:
        - /^v[0-9]/

before_install:
    - npm i -g npm

install:
    - npm ci

script:
    - NODE_ENV=production npm run build
