dist: xenial
language: node_js
sudo: false

branches:
    except:
        - /^v[0-9]/

before_install:
    - npm i -g npm

install:
    - npm i -g firebase firebase-tools
    - firebase setup:emulators:firestore

script:
    - npm run --prefix=./firestore/rules-test test
