dist: xenial
language: node_js
sudo: false

branches:
    except:
        - /^v[0-9]/

before_install:
    - npm i -g npm
    - npm i -g firebase firebase-tools
    - git clone https://jblew:${GH_TOKEN}@github.com/jblew/amerykahospital-personalizedadvice-settings.git functions/src/settings
    - |
      if [[ $TRAVIS_BRANCH == "production" ]]; then
        firebase use production
        functions/src/settings/scripts/select-production.sh
        echo "Using production environment"
      else
        firebase use preprod
        functions/src/settings/scripts/select-preprod.sh
        echo "Using preprod environment"
      fi
    - cat functions/src/settings/index.ts

install:
    - npm install --prefix=./functions
    - firebase setup:emulators:firestore
    - firebase setup:emulators:database

script:
    - npm run --prefix=./functions test
    - npm run --prefix=./functions verify

deploy:
    - provider: script
      script: bash -c "npx firebase deploy --only functions"
      skip_cleanup: true
      on:
          tags: false
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(preprod|production)$
